CREATE TABLE IF NOT EXISTS person
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    last_name  VARCHAR(50) NOT NULL,
    first_name VARCHAR(50) NOT NULL,
    address    VARCHAR(50) NOT NULL,
    gender     VARCHAR(50) NOT NULL,
    CONSTRAINT person_pkey PRIMARY KEY (id)
);