CREATE TABLE IF NOT EXISTS book
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    author      TEXT,
    launch_date TIMESTAMP(6) NOT NULL,
    price       DECIMAL(65,2) NOT NULL,
    title       TEXT,
    CONSTRAINT books_pkey PRIMARY KEY (id)
);
