spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/SBPJ_Studies
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
    show-sql: false
    open-in-view: false
logging:
  level:
    root: info